### ISSUE TITLE
Armando: Decide on State Management - redux or context

### ISSUE THREAD

**Issue by jondhill333** [chingu-voyages/v28-bears-team-10#14]

**Comment by guarmo** [comment]
My thoughts on state management: 

I love using Redux cause it’s incredibly powerful. It has a lot of boilerplate and extra lines of code but it comes with its advantages one of which (but not the only one) being its devtools. It’s also meant to be used in larger applications which is why it’s probably not necessary to use in our case.

Considering the fact that also the rest of the team has not worked with Redux before I would definitely use a combination of useContext and useReducer to share and manage state across the application.
In our meeting, I’d love to walk you through the way I’d structure this in our app. It’s basically Brad Traversy’s way of doing it.

I’ll be referencing this: https://github.com/guarmo/Progress-Updates/tree/main/Day%20109%20-%20ContactKeeper%20-%20final/client/src
